#!/bin/bash

set -eux

# Import GPG keys if available

if [ -f ~/host-public.key ]; then
    gpg --batch --import ~/host-public.key
fi
if [ -f ~/host-private.key ]; then
    gpg --batch --import ~/host-private.key
    # Set the key to trust ultimate
    echo -e "5\ny\n" | gpg --batch --yes --command-fd 0 --edit-key $(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2) trust quit
fi

# Add user to host docker group using UID

if [ -S /var/run/docker.sock ]; then
    if [ ! `getent group docker` ]; then
        DOCKER_GID=`stat -c '%g' /var/run/docker.sock`
        sudo groupadd -g $DOCKER_GID docker
        sudo usermod -aG docker $(getent passwd | awk -F: -v uid="`id -u`" '$3 == uid {print $1}')
    fi
fi

sudo su - `whoami`
exec /bin/zsh $@
