#!/bin/sh

set -eux

# Import GPG keys if available

if [ -f ~/host-public.key ]; then
    gpg --batch --import ~/host-public.key
fi
if [ -f ~/host-private.key ]; then
    gpg --batch --import ~/host-private.key
    # Set the key to trust ultimate
    gpg --batch --yes --edit-key $(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2) trust quit
fi

/bin/zsh $@
