#!/bin/bash -e

git pull
git add .
git commit -m "Update config on $(date)"
git push

DOCKERFILE_DIR=$PWD

docker build -t yashanand1910/dev -t dev -f $DOCKERFILE_DIR/Dockerfile .
(
    cd ~ # since we are accessing some files from ~ during build
    docker build --build-arg DOCKERFILE_DIR=$DOCKERFILE_DIR -t yashanand1910/dev-private -t dev-private -f $DOCKERFILE_DIR/private.Dockerfile .
)

docker push yashanand1910/dev:latest
docker push yashanand1910/dev-private:latest

docker system prune -f --volumes
