#!/bin/bash -eux

git pull
git add .
git commit -m "Update config on $(date)"
git push || true

docker build -t yashanand1910/dev -t dev .

DOCKERFILE_DIR=$PWD
(
    cd $HOME # since we are accessing some files from $HOME during build
    docker build \
      --build-arg GITHUB_KEY=$GITHUB_KEY \
      --build-arg DOCKERHUB_KEY=$DOCKERHUB_KEY \
      -t yashanand1910/dev-private -t dev-private -f $DOCKERFILE_DIR/private.Dockerfile .
)

docker push yashanand1910/dev:latest
docker push yashanand1910/dev-private:latest

docker system prune -f --volumes
