#!/bin/bash -e

mkdir -p ~/.ssh

chmod 700 ~/.ssh
chmod 600 ~/.ssh/*

# Perform any SSH-related operations here
# For example, clone a private repository
# git clone git@github.com:your-repo/your-private-repo.git

# Execute the provided command
exec "$@"
