#!/bin/bash

while true; do
    nvidia-smi dmon -c 1 | tail -1 > /tmp/gpu-smi
    cat /tmp/gpu-smi | awk -F' ' '{print $3}' > /tmp/gpu-gtemp
    cat /tmp/gpu-smi | awk -F' ' '{print $5}' > /tmp/gpu-sm
    sleep 5
done;
